name: Greetings

on: [pull_request_target, issues]

env:
  SLACK_NOTIFY: false

# Declare default permissions as read only.
permissions: read-all

jobs:
  greeting:
    name: Handle Greetings
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Handle greetings
      uses: actions/first-interaction@1dbfe1ba5525b8257e1f259b09745bee346d62d8 # v1.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for raising your first issue - all contributions to this project are welcome!"
        pr-message: "Thank you for raising your first pull request - all contributions to this project are welcome!"

  slack-workflow-status:
    if: always() && github.actor != 'dependabot[bot]'
    name: Slack Post Workflow Notification
    needs:
      - greeting
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notifications
        if: ${{ env.SLACK_NOTIFY == 'true' && github.event_name == 'push' }}
        uses: Gamesight/slack-workflow-status@26a36836c887f260477432e4314ec3490a84f309 # v1.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          include_jobs: on-failure
          include_commit_message: true
