name: Purge obsolete workflow runs

on:
  workflow_dispatch:
  schedule:
    - cron: '55 4 * * 1'

env:
  SLACK_NOTIFY: false

# Declare default permissions as read only.
permissions: read-all

jobs:
  purge-obsolete-workflows:
    name: Purge obsolete workflow runs
    runs-on: ubuntu-latest
    steps:
      - name: Purge obsolete workflow runs
        uses: otto-de/purge-deprecated-workflow-runs@b42231c124eee1f9daaafa37ab0c85621b0e4c53 # v 1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - purge-obsolete-workflows
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notifications
        if: ${{ env.SLACK_NOTIFY == 'true' && github.event_name == 'push' }}
        uses: Gamesight/slack-workflow-status@68bf00d0dbdbcb206c278399aa1ef6c14f74347a # v1.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          include_jobs: on-failure
          include_commit_message: true
