name: Test action (PHP)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  SLACK_NOTIFY: true

jobs:
  test-output-method-setup:
    name: min-version=7.3
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: php
          min-version: "7.3"

  test-output-method-load:
    name: min-version=7.3
    needs: test-output-method-setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-matrix: ${{fromJson(needs.test-output-method-setup.outputs.version-matrix)}}
    steps:
      - name: Setup PHP ${{ matrix.version-matrix }}
        uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # 2.30.4
        with:
          php-version: ${{ matrix.version-matrix }}

  test-output-method-setup-eol:
    name: min-version=EOL
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: php

  test-output-method-load-eol:
    name: min-version=EOL
    needs: test-output-method-setup-eol
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-matrix: ${{fromJson(needs.test-output-method-setup-eol.outputs.version-matrix)}}
    steps:
      - name: Setup PHP ${{ matrix.version-matrix }}
        uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # 2.30.4
        with:
          php-version: ${{ matrix.version-matrix }}


  test-output-method-setup-highest-only:
    name: Highest version only
    runs-on: ubuntu-latest
    outputs:
      highest-version: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: php
          highest-only: true

  test-output-method-load-highest-only:
    name: Build for highest version only
    needs: test-output-method-setup-highest-only
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP ${{ needs.test-output-method-setup-highest-only.outputs.highest-version }}
        uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # 2.30.4
        with:
          php-version: ${{ needs.test-output-method-setup-highest-only.outputs.highest-version }}

  test-output-method-setup-highest-only-patch-only:
    name: Highest version only (Patch Only)
    runs-on: ubuntu-latest
    outputs:
      highest-version: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: php
          highest-only: true
          remove-patch-version: true

  test-output-method-load-highest-only-patch-only:
    name: Build for highest version only (Patch Only)
    needs: test-output-method-setup-highest-only-patch-only
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP ${{ needs.test-output-method-setup-highest-only-patch-only.outputs.highest-version }}
        uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # 2.30.4
        with:
          php-version: ${{ needs.test-output-method-setup-highest-only-patch-only.outputs.highest-version }}

  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - test-output-method-load
      - test-output-method-load-eol
      - test-output-method-load-highest-only
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notifications
        if: ${{ env.SLACK_NOTIFY == 'true' && github.event_name == 'push' }}
        uses: Gamesight/slack-workflow-status@68bf00d0dbdbcb206c278399aa1ef6c14f74347a # v1.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          include_jobs: on-failure
          include_commit_message: true
