name: Test action (Terraform)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  SLACK_NOTIFY: true

jobs:
  test-output-method-setup:
    name: min-version=1.1
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: terraform
          min-version: "1.1"

  test-output-method-load:
    name: min-version=1.2
    needs: test-output-method-setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-matrix: ${{fromJson(needs.test-output-method-setup.outputs.version-matrix)}}
    steps:
      - name: Setup Terraform ${{ matrix.version-matrix }}
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: ${{ matrix.version-matrix }}

  test-output-method-setup-eol:
    name: min-version=EOL
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: terraform

  test-output-method-load-eol:
    name: min-version=EOL
    needs: test-output-method-setup-eol
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-matrix: ${{fromJson(needs.test-output-method-setup-eol.outputs.version-matrix)}}
    steps:
      - name: Setup Terraform ${{ matrix.version-matrix }}
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: ${{ matrix.version-matrix }}

  test-output-method-setup-highest-only:
    name: Highest version only
    runs-on: ubuntu-latest
    outputs:
      highest-version: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: terraform
          highest-only: true

  test-output-method-load-highest-only:
    name: Build for highest version only
    needs: test-output-method-setup-highest-only
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform ${{ needs.test-output-method-setup-highest-only.outputs.highest-version }}
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: ${{ needs.test-output-method-setup-highest-only.outputs.highest-version }}

  test-output-method-setup-highest-only-strip-patch:
    name: Highest version only (Strip Patch)
    runs-on: ubuntu-latest
    outputs:
      highest-version: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: terraform
          highest-only: true
          remove-patch-version: true

  test-output-method-load-highest-only-strip-patch:
    name: Build for highest version only (Strip Patch)
    needs: test-output-method-setup-highest-only-strip-patch
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform ${{ needs.test-output-method-setup-highest-only-strip-patch.outputs.highest-version }}
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: ${{ needs.test-output-method-setup-highest-only-strip-patch.outputs.highest-version }}

  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - test-output-method-load
      - test-output-method-load-eol
      - test-output-method-load-highest-only
      - test-output-method-load-highest-only-strip-patch
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notifications
        if: ${{ env.SLACK_NOTIFY == 'true' && github.event_name == 'push' }}
        uses: Gamesight/slack-workflow-status@68bf00d0dbdbcb206c278399aa1ef6c14f74347a # v1.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          include_jobs: on-failure
          include_commit_message: true
