name: Test action (Node)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  SLACK_NOTIFY: true

jobs:
  test-output-method-setup:
    name: min-version=18
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: node
          min-version: "18"

  test-output-method-load:
    name: min-version=18
    needs: test-output-method-setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-matrix: ${{fromJson(needs.test-output-method-setup.outputs.version-matrix)}}
    steps:
      - name: Setup Node ${{ matrix.version-matrix }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ matrix.version-matrix }}

  test-output-method-setup-eol:
    name: min-version=EOL
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: node

  test-output-method-load-eol:
    name: min-version=EOL
    needs: test-output-method-setup-eol
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-matrix: ${{fromJson(needs.test-output-method-setup-eol.outputs.version-matrix)}}
    steps:
      - name: Setup Node ${{ matrix.version-matrix }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ matrix.version-matrix }}

  test-output-method-setup-highest-only:
    name: Highest version only
    runs-on: ubuntu-latest
    outputs:
      highest-version: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: node
          highest-only: true

  test-output-method-load-highest-only:
    name: Build for highest version only
    needs: test-output-method-setup-highest-only
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node ${{ needs.test-output-method-setup-highest-only.outputs.highest-version }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ needs.test-output-method-setup-highest-only.outputs.highest-version }}

  test-output-method-setup-highest-only-strip-patch:
    name: Highest version only (Strip Patch)
    runs-on: ubuntu-latest
    outputs:
      highest-version: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: node
          highest-only: true
          remove-patch-version: true

  test-output-method-load-highest-only-strip-patch:
    name: Build for highest version only (Strip Patch)
    needs: test-output-method-setup-highest-only-strip-patch
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node ${{ needs.test-output-method-setup-highest-only-strip-patch.outputs.highest-version }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ needs.test-output-method-setup-highest-only-strip-patch.outputs.highest-version }}

  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - test-output-method-load
      - test-output-method-load-eol
      - test-output-method-load-highest-only
      - test-output-method-load-highest-only-strip-patch
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notifications
        if: ${{ env.SLACK_NOTIFY == 'true' && github.event_name == 'push' }}
        uses: Gamesight/slack-workflow-status@68bf00d0dbdbcb206c278399aa1ef6c14f74347a # v1.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          include_jobs: on-failure
          include_commit_message: true
