name: Test action (Perl)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  SLACK_NOTIFY: true

jobs:
  test-output-method-setup:
    name: min-version=5.34
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: perl
          min-version: "5.34"

  test-output-method-load:
    name: min-version=5.34
    needs: test-output-method-setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-matrix: ${{fromJson(needs.test-output-method-setup.outputs.version-matrix)}}
    steps:
      - name: Setup Perl ${{ matrix.version-matrix }}
        uses: shogo82148/actions-setup-perl@35426a57f184a35daee329bb17ae49332ff8a422 # v1.23.1
        with:
          perl-version: ${{ matrix.version-matrix }}

  test-output-method-setup-eol:
    name: min-version=EOL
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: perl

  test-output-method-load-eol:
    name: min-version=EOL
    needs: test-output-method-setup-eol
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-matrix: ${{fromJson(needs.test-output-method-setup-eol.outputs.version-matrix)}}
    steps:
      - name: Setup Perl ${{ matrix.version-matrix }}
        uses: shogo82148/actions-setup-perl@35426a57f184a35daee329bb17ae49332ff8a422 # v1.23.1
        with:
          perl-version: ${{ matrix.version-matrix }}

  test-output-method-setup-highest-only:
    name: Highest version only
    runs-on: ubuntu-latest
    outputs:
      highest-version: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: perl
          highest-only: true

  test-output-method-load-highest-only:
    name: Build for highest version only
    needs: test-output-method-setup-highest-only
    runs-on: ubuntu-latest
    steps:
      - name: Setup Perl ${{ needs.test-output-method-setup-highest-only.outputs.highest-version }}
        uses: shogo82148/actions-setup-perl@35426a57f184a35daee329bb17ae49332ff8a422 # v1.23.1
        with:
          perl-version: ${{ needs.test-output-method-setup-highest-only.outputs.highest-version }}

  test-output-method-setup-highest-only-patch-only:
    name: Highest version only (Patch Only)
    runs-on: ubuntu-latest
    outputs:
      highest-version: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Get versions
        uses: ./
        id: get-versions
        with:
          language: perl
          highest-only: true
          remove-patch-version: true

  test-output-method-load-highest-only-patch-only:
    name: Build for highest version only (Patch Only)
    needs: test-output-method-setup-highest-only-patch-only
    runs-on: ubuntu-latest
    steps:
      - name: Setup Perl ${{ needs.test-output-method-setup-highest-only-patch-only.outputs.highest-version }}
        uses: shogo82148/actions-setup-perl@35426a57f184a35daee329bb17ae49332ff8a422 # v1.23.1
        with:
          perl-version: ${{ needs.test-output-method-setup-highest-only-patch-only.outputs.highest-version }}

  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - test-output-method-load
      - test-output-method-load-eol
      - test-output-method-load-highest-only
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notifications
        if: ${{ env.SLACK_NOTIFY == 'true' && github.event_name == 'push' }}
        uses: Gamesight/slack-workflow-status@26a36836c887f260477432e4314ec3490a84f309 # v1.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          include_jobs: on-failure
          include_commit_message: true
